# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: nbktechnosys/myjavaimages2dec22:1  # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
